name: Build and Release APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Mengunci sertifikat permanen agar semua update memiliki signature yang sama persis
      - name: Restore Permanent Keystore
        run: |
          echo "MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBcAGCSqGSIb3DQEHAaCCBbEEggWtMIIFqTCCBaUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFAtWR5ggmEsdCWYprp/SFfIXVfheAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ/h23xXyj5i+/MS0TrZS2ogSCBNBE88oePCkiffFg4Bkkkk7sWx1ywR/yYpM+EhrMV02x5casD3eYGGLqwj6aBylHQ800u2lWCjhB7HQ1r2sd98pn2bGdgg/06dK+URGX40a8PLqDpTwwjZUH55iqvDCbpgtSYg94JEXu51Spu3R5i38YMPb2C0Ku6kWx/GePRq/YEWpVukbZC4P/+JsSBgf2YjN8xGlzh90P02i9+eL9wWq1/nV/ki6Oa7BKFzuLULI+1Frj0WkVCOWlKWG30qhfvw24yRvHvt2p+aWjQahQHrEVYIViDKl8dS7gVTbdpXK3EvS+kbEHXl9tR6u6FU/9S3j5dTt4G9APlGZGFF2OfVELzaaQ0C/CDNX3nvz0Eejr95RBDuOCkBmn7xHt81anPLu7nkR57f90snkr/MNGcLHUscdUQQiY7HgSOgAsSBui5s51+aBmQGqX+BQENIWFLLXRqvATS2rceaOY6TIhYDUVTxAnHE3nhWzED963Ux2KIsuGqs2Ieeg9N7Vs13k5k5KX0MrSZCHK2qJ6H/CDRKEb5ICZ2i9bMyrD4JSC1gRe9H8gZdCy3ooDP9JQxWBe/VNq4Cl4JvOldUyrkUIPNedrCpWpCquhkbs2HBTNVCH4y4lte/pm6yGSTpM3AFMs7QHv2fEiGnrL5sUmW+tPBvh4WAIT3PgvKSwhfb00GkJ8y+gZPMoUmtQaJm2qNrBZKcYKgTLvuc0qRQkjpugPlOr/fAKMQy9V0PQV4RWcXfWDwS62lRa+ehoktK/m9dvbV09HZKLPmweJFXW5jdIIZDB736AAkQ/zEgAyV5XAS9IwskoUP6wFCpBPky8ND99rvet20+isQ2mIIgCgRwwoned2BybmWquv9v4shERuW0ZF4H9deZhoT7lMdLavj6dArRXwav4cAg263AzI/HSZiTKqhkDIIuHiSxEnXefMe7PbrJP8AlzbM8rV7USLRL+WesXnSE29vj7qlfEWRtLPfiMJV2mdXX0D/JwnYs/ZYXJ3DqKoL9ZldOD7xqWtrSUZxAoWU2PbfzU1HFF1TSZQh/GSAJad021jAN9suz1fKtGNu+HDvnBkNkKCZcHFXu+/9RlIiFsYX0bIDEq8iWTYoc+A89TFXJDF7afXY10UTpfnmR1fH7p8PtVBkLurF0EOp+GldV9DBG8sEvEwya3xgxykpOez2k/D2otvF5u9+RqSEkqBTUOdtLMkCPuhADYNeCY6obPf4P/5lAOwSqYPKoFlGEHqH8o8i2gNXLPNdyHHDfW5bGCl8Dl+gbDiCEINU/fAcvO4fIWBGSAe6Tcc+U70Q8LVJksJsSqirK93F+QKMA/KMBnsnSOkswqyu+v2tc1CaKu581CAgWDytlqTF40VKk45pNBFWdYTTTJdsZ9Ao0UKdJf8tcMgIM/kEtkHFlx8yXMlqPgJ1wmcYwT4VheqM1ZBr0GBQlrw4s2JHsfaZOZ1aQ1zwuiiUPdxQVJDo90KnV/yxVBKITsvBM+rN42dT9iUnSESjS3igSWEn4da0aqrpnJYTISbZWC78yAT9a4VvqGb+T0h/sjrgeIByjL8hR9GFQZXWgblo3j1KFyS3cwDDmPJOSP+NW4ts85RPbGn1DF+ow107ll6OEhKTMdj+mIxSzNUVwQCuXd6CxrEgDFSMC0GCSqGSIb3DQEJFDEgHh4AYQBuAGQAcgBvAGkAZABkAGUAYgB1AGcAawBlAHkwIQYJKoZIhvcNAQkVMRQEElRpbWUgMTc4ODAxNjE2OTM0NDCCBDEGCSqGSIb3DQEHBqCCBCIwggQeAgEAMIIEFwYJKoZIhvcNAQcBMGYGCSqGSIb3DQEFDTBZMDgGCSqGSIb3DQEFDDArBBTGXJB8vMG/euMaKO3Mmy6GO1R+CQICJxACASAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEF6K8NM3r9qtohrRgroLFciAggOgvFOHqHDhFToDlI5A2Kt6w+N8uoMEhWdvEBY3IJqvsZCOnYW1Kfae6f3dQ/jBjpj9vQ6o+T/KuEOtRW5XO8YgCUztX9ZaCMBDYKDw2r8JE7nvXhOyoYCOQR7xDT6a25bU82g1dHRlpGUw2rQbOzPNOoDNDz13eUx32QuClPG3OoeLEI+AGBYDdvePCfV/5BlaZXY6KBJvhCWI+l7U8IaSus7f3mBsf66rhTgvTegcZ4LE1Rn7NE7It4VFG9PiAa7w3i9+AtjAZdi4M+aAWJ8a5ctC9NL0Dor5DcXqDSo2NssvR0ds8uF76KsSgyydIqJzqUiVLv1ocSg4PAS9+nbW9On91Hzf+mlECZLLRafiErsJl+MViyvLCgJh+Vm+PqLbH/Nq4yLYOaC+gtOLliRXmisV9Ld/X3hVC8CnW6jsKukphk9/7NwpZcdIXCIlrQY2Mscav8wUYtFcIaCdoolgCPAauZ7ny+MJ4A/MOFPp9W2vQtanwKuc5O+I+J0eW5TBJ+WBHPQRR0JmeEsGfOfX+itAVEhz6nLWGqcfL9N7dcy03FLUF0RZGZNfuBqkkIp/Qp72reY8X1CGVS38qcF46Jyzaxp5RXvTKq1hWTsWPpGMIQ98TmNdJMINwXqP2VuUptX3sczGLFhEyOp5ci6cuf/8fncreIYsIoq1lIpIO+u14hJ91VPzsG2VttHTz16hdL8voJ6MUA92TSlmC5woAeM8w5Lo8M8b+CO8Ew50YplR+x+BopsP2xBAqcrru14lW3ofI00NZU1300fFAcGM/GiIxlKvSj+OGkTEMY++TZ8oF566QuThrEqpvm3ZsGBbQ9PX4U3GYEMibfOaDW7x93RITwq8sVyoRQT8a9cSEuJbpqt9YTC4eX0m1W2Bz22RDGlJunrjq0XrdVlT20iP/ns00VajhRBDi0hZCt4LZy2U7thtMqG9K1b+BwzrfDrA3GnvDrLsRD6sANyBcbcms2ttStdHectOYu7//CS5AjJh2E1clKNR8yKbSoSy3YG2zZ7nQyKWA3QwtG2hjtyoJEEVbdD71SzJM5d30QDVq+m+pbuCyzo7fA6xd3WrOx0bwq8pkAR2A8EIEnjUWq2oavA3rpNQ4eVZBjqQ4eU0/I3vFiqtde+SzAETOnhTkieAmDaJOLeVJu1DlfDaJw6t+ynZ0d6GEfDhp1IWg8OzP2vZtN889pZbcJ1jv37twf54NDvqMFt10UfuQBLjtP4aCTBNMDEwDQYJYIZIAWUDBAIBBQAEINhaYfKfe38dkTF1WJNld0MZf8HCdw6PFXB0ZfTmFeWUBBQL7Y5X32Es41YVLjpukikX1bW4KgICJxA=" | base64 -d > app/debug.keystore

      - name: Build Debug APK
        run: gradle assembleDebug -PappVersionCode=${{ github.run_number }} --stacktrace

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          name: "Update Aplikasi Presensi (Build ${{ github.run_number }})"
          body: "Rilis versi terbaru otomatis dari GitHub Actions."
          draft: false
          prerelease: false
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
